### ISSUE TITLE
Order is not preserved.

### ISSUE THREAD

**Issue by Mr-Jonas** [hjson/hjson-cpp#10]
**First of all. thank you for making this.**
hjson is vastly more fun to work with due to no "" all over.
Anyway, hjson-cpp seems to sort the hjson elements when i do
Value dat = Hjson::Unmarshal(hjsonStrInput);
std::string hjsonOut = Hjson::Marshal(dat);

I used it for an editor so it is very confusing that stuff moves around.
Is there any way to keep the actual order of the elements?
I used hjson for a templates system and the order is kinda important
as alphabetically will mess up the natural grouping.

**Comment by trobro** [comment]
I'm glad you like Hjson!

There is currently no way to keep the order, but maybe I can add it as an option to `MarshalWithOptions()`.

**Comment by Mr-Jonas** [comment]
Hi. That would be wonderful if it is possible with MarshalWithOptions(). Would fit right in there.
(i actually tried that as it sounded promising :) 
Thank you in advance.

**Comment by hongguangxu** [comment]
Hi, when I run function Unmarshal in multi-threads, why it consumes more time than in single thread?
any idea for this, thanks!

**Comment by trobro** [comment]
Added option `preserveInsertionOrder` for `MarshalWithOptions`. The default value is `false`, but I might change that to `true` in a future release 2.0.

**Comment by Mr-Jonas** [comment]
Oh nice! cant wait to check it out. Then my "reformat" wont move things around. thank you.

**Comment by trobro** [comment]
Great, no problem!
