### ISSUE TITLE
missing output operator

### ISSUE THREAD

**Issue by bstarynk** [hjson/hjson-cpp#20]
I am missing some 
`       std::ostream& operator << (std::ostream&, HJson::Value);`
operator to be able to code in a C++ friendly way `std::cout << hjv`  after having filled some `HJson::Value hjv;` (at least for debugging purposes).

A trivial (but not very efficient) implementation might be 

```
std::ostream& operator << (std::ostream&out, HJson::Value hjv) {
  out << HJson::MarshalJson(hjv);
  return out;
}
```

**Comment by trobro** [comment]
Thanks for the suggestion, works nicely.

**Comment by bstarynk** [comment]
FWIW, in [RefPerSys](http://refpersys.org/), we decided to give up completely HJson (since [that pull request](https://github.com/bstarynk/hjson-cpp) was not accepted upstream). We are now using [JsonCPP](https://github.com/open-source-parsers/jsoncpp) which has an API very similar to what we proposed, and perfectly suiting our needs (even if [Json](http://json.org/) files are slightly more verbose than HJson ones).

Happy New Year 2020. Regards.

-- 
[Basile Starynkevitch](http://starynkevitch.net/Basile/index_en.html), near Paris, France
<basile@starynkevitch.net>

**Comment by trobro** [comment]
Thanks for the info, happy new year!
