### ISSUE TITLE
Add it to vcpkg

### ISSUE THREAD

**Issue by Zingam** [hjson/hjson-cpp#9]
Add it to vcpkg package manager and also make it as a header only library?

**Comment by trobro** [comment]
Thanks for the suggestions! Personally I prefer to not have any implementations in headers, but I might look into vcpkg in the future when I have time.

**Comment by trobro** [comment]
I've had a look at vcpkg now. Adding Hjson to vcpkg can be done by signing a contributor-agreement with Microsoft and creating a PR for a folder under `ports` in their `vcpkg` repository. The folder should contain a vcpkg-specific Cmake file, like for yaml:

https://github.com/Microsoft/vcpkg/tree/master/ports/yaml-cpp

I have no plans to start using vcpk myself, so I will close this as wontfix for now.
